# AWS CodeBuild buildspec to build the sentiment_analysis_application docker image

# This requires the following environment variables be set on the Project:
# AWS_DEFAULT_REGION (Supplied by CodeBuild)
# AWS_ACCOUNT_ID
# IMAGE_REPO_NAME
# IMAGE_TAG

#Required mapping. Represents the buildspec version.
version: 0.2

env:
  variables:
      AWS_REGION: us-west-1
      AWS_ACCOUNT_ID: 289847908642
      AWS_SERVICE_NAME: .dkr.ecr.
      AWS_DOMAIN_NAME: .amazonaws.com
      IMAGE_NAME: husain-sentiment-analysis-docker-image
      CONTAINER_NAME: husain-sentiment-analysis-docker-container  

#Required sequence. Represents the commands CodeBuild runs during each phase of the build. 
phases:
  pre_build:
    commands:
      - REPOSITORY_URL="$AWS_ACCOUNT_ID$AWS_SERVICE_NAME$AWS_REGION$AWS_DOMAIN_NAME"
      - echo Logging in to Amazon ECR..,
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - docker image tag $IMAGE_NAME:latest $REPOSITORY_URL/$IMAGE_NAME:latest
      - echo image name =  $IMAGE_NAME:latest
      - echo image url = $REPOSITORY_URL/$IMAGE_NAME:latest  
      - echo Build and tag stage successfully completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URL/$IMAGE_NAME:latest
      - echo Writing image definitions file....
      - printf '[{"name":"'"$CONTAINER_NAME"'","imageUri":"'"$REPOSITORY_URL"'/'"$IMAGE_NAME"':latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`
artifacts:
  files: imagedefinitions.json

